$(document).ready(function(){
  $("#nav1").click(function(){
    $(".highlight").attr("style","margin-left:0px;");
  });
  $("#nav2").click(function(){
    $(".highlight").attr("style","margin-left:33.3%;");
  });
  $("#nav3").click(function(){
    $(".highlight").attr("style","margin-left:66.6%");
  });
})
